name: build-and-test
on: [push]
jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Get cmake
        uses: lukka/get-cmake@latest
      - name: Install newer g++
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
      - name: Get conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.59.0
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Make build directory
        run: mkdir -p build
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-11 -S. -B./build -G Ninja
      - name: Compile
        run: cd build && ninja
      - name: Test
        run: cd build/tests && ctest --output-on-failure 
