name: build-and-test
on: [push]
jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Get cmake
        uses: lukka/get-cmake@latest
      - name: Get conan
        uses: turtlebrowser/get-conan@main
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Make build directory
        run: mkdir -p build
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++ -S. -B./build -G Ninja
      - name: Compile
        run: cd build && ninja
      - name: Test
        run: ctest --output-on-failure 